version: '3.7'

services:
  frontend:
    container_name: frontend
    build: ./TCC
    volumes:
      - frontend:/var/www/html
    networks:
      - autodroid_autodroid_network

  nginx:
    container_name: nginx-frontend
    build: ./nginx
    ports:
      - 3000:3000
    volumes:
      - frontend:/usr/share/nginx/html
    depends_on:
      - frontend
    networks:
      - autodroid_autodroid_network

volumes:
  frontend:

networks:
  autodroid_autodroid_network:
    external: true
